cartas = {
	'maso'	:	[
		{'color': 'Corazon', 'valor': 'A'}, 
		{'color': 'Corazon', 'valor': '2'}, 
		{'color': 'Corazon', 'valor': '3'},
		{'color': 'Corazon', 'valor': '4'}, 
		{'color': 'Corazon', 'valor': '5'}, 
		{'color': 'Corazon', 'valor': '6'}, 
		{'color': 'Corazon', 'valor': '7'}, 
		{'color': 'Corazon', 'valor': '8'}, 
		{'color': 'Corazon', 'valor': '9'}, 
		{'color': 'Corazon', 'valor': 'D'}, 
		{'color': 'Corazon', 'valor': 'J'}, 
		{'color': 'Corazon', 'valor': 'Q'}, 
		{'color': 'Corazon', 'valor': 'K'}, 
		{'color': 'Diamante', 'valor': 'A'}, 
		{'color': 'Diamante', 'valor': '2'}, 
		{'color': 'Diamante', 'valor': '3'}, 
		{'color': 'Diamante', 'valor': '4'}, 
		{'color': 'Diamante', 'valor': '5'}, 
		{'color': 'Diamante', 'valor': '6'}, 
		{'color': 'Diamante', 'valor': '7'}, 
		{'color': 'Diamante', 'valor': '8'}, 
		{'color': 'Diamante', 'valor': '9'}, 
		{'color': 'Diamante', 'valor': 'D'}, 
		{'color': 'Diamante', 'valor': 'J'}, 
		{'color': 'Diamante', 'valor': 'Q'}, 
		{'color': 'Diamante', 'valor': 'K'}, 
		{'color': 'Espada', 'valor': 'A'}, 
		{'color': 'Espada', 'valor': '2'}, 
		{'color': 'Espada', 'valor': '3'}, 
		{'color': 'Espada', 'valor': '4'}, 
		{'color': 'Espada', 'valor': '5'}, 
		{'color': 'Espada', 'valor': '6'}, 
		{'color': 'Espada', 'valor': '7'}, 
		{'color': 'Espada', 'valor': '8'}, 
		{'color': 'Espada', 'valor': '9'}, 
		{'color': 'Espada', 'valor': 'D'}, 
		{'color': 'Espada', 'valor': 'J'}, 
		{'color': 'Espada', 'valor': 'Q'}, 
		{'color': 'Espada', 'valor': 'K'}, 
		{'color': 'Trebol', 'valor': 'A'}, 
		{'color': 'Trebol', 'valor': '2'}, 
		{'color': 'Trebol', 'valor': '3'}, 
		{'color': 'Trebol', 'valor': '4'}, 
		{'color': 'Trebol', 'valor': '5'}, 
		{'color': 'Trebol', 'valor': '6'}, 
		{'color': 'Trebol', 'valor': '7'}, 
		{'color': 'Trebol', 'valor': '8'}, 
		{'color': 'Trebol', 'valor': '9'}, 
		{'color': 'Trebol', 'valor': 'D'}, 
		{'color': 'Trebol', 'valor': 'J'}, 
		{'color': 'Trebol', 'valor': 'Q'}, 
		{'color': 'Trebol', 'valor': 'K'}
	], 
	'colores'	:	[
		'Corazon',
		'Diamante', 
		'Espada', 
		'Trebol'
	], 
	'valores'	:	'A23456789DJQK'
}


